const A4_LANDSCAPE_WIDTH_MM = 297;
const A4_LANDSCAPE_HEIGHT_MM = 210;

export const SCHEMATIC_SVG_WIDTH = 1400;
export const SCHEMATIC_SVG_HEIGHT = Math.round(
  (SCHEMATIC_SVG_WIDTH * A4_LANDSCAPE_HEIGHT_MM) / A4_LANDSCAPE_WIDTH_MM,
);
