// Generated by scripts/generate-ti-reference-examples.ts.
// Do not edit by hand; update examples/ti-reference-examples.json.
import { OPA371DDBVR } from "../lib/chips/OPA371DDBVR.tsx";
import "tscircuit";

/**
 * OPA371D Low-Side Current-Sense Reference
 *
 * TI source: https://www.ti.com/lit/gpn/OPA371D
 * Document viewer: https://www.ti.com/document-viewer/OPA371D/datasheet/GUID-03C60932-F0E0-4CDB-9FB0-C73F5C680C80
 * Figure 7-1: Low-Side, Current-Sensing Application
 * Figure asset: https://www.ti.com/ods/images/SLVSM48A/GUID-B2DF1A69-DA22-4522-9874-1574F18368E7-low.gif
 * Scope: Complete Figure 7-1 signal path and feedback network; ZLOAD remains symbolic because TI does not specify its impedance.
 */
export default () => (
  <board routingDisabled schMaxTraceDistance={20}>
    <OPA371DDBVR name="U1" noSchematicRepresentation />

    <schematicsymbol
      name="U1_OPAMP"
      displayName="U1"
      chipRef=".U1"
      symbolName="opamp_with_power_right"
      schX={0}
      schY={0}
      connections={{
        inp1: ".U1 > .pin3",
        inp2: ".U1 > .pin4",
        out: ".U1 > .pin1",
        "V+": ".U1 > .pin5",
        "V-": ".U1 > .pin2",
      }}
    />

    <net
      name="GND"
      isGroundNet
      connectsTo={["GND_SHUNT.pin1", "GND_DEVICE.pin1", "GND_GAIN.pin1"]}
    />

    {/* ZLOAD; TI does not specify an impedance value. */}
    <schematicsymbol
      name="Z_LOAD"
      displayName="ZLOAD"
      symbolName="resistor_down"
      schX={-2}
      schY={1.35}
    />

    <resistor
      name="R_SHUNT"
      resistance="0.1ohm"
      footprint="2512"
      schX={-2}
      schY={-0.35}
      schRotation="-90deg"
    />

    <resistor
      name="R_F"
      resistance="57.6k"
      footprint="0402"
      schX={1.5}
      schY={-0.4}
      schRotation="-90deg"
    />

    <resistor
      name="R_G"
      resistance="1.2k"
      footprint="0402"
      schX={1.5}
      schY={-1.5}
      schRotation="-90deg"
    />

    {/* VBUS rail */}
    <schematicsymbol
      name="VBUS_RAIL"
      displayName="VBUS"
      symbolName="rail_up"
      schX={-2}
      schY={2.2}
    />

    {/* 5 V device supply */}
    <schematicsymbol
      name="V5_RAIL"
      displayName="5 V"
      symbolName="rail_up"
      schX={-0.1}
      schY={1}
    />

    {/* RSHUNT ground return */}
    <schematicsymbol
      name="GND_SHUNT"
      displayName=""
      symbolName="digital_ground_up"
      schX={-2}
      schY={-1.1}
    />

    {/* device negative supply ground */}
    <schematicsymbol
      name="GND_DEVICE"
      displayName=""
      symbolName="digital_ground_up"
      schX={-0.09}
      schY={-1}
    />

    {/* RG ground return */}
    <schematicsymbol
      name="GND_GAIN"
      displayName=""
      symbolName="digital_ground_up"
      schX={1.5}
      schY={-2.3}
    />

    {/* VOUT terminal */}
    <schematicsymbol
      name="VOUT_TERMINAL"
      displayName="VOUT"
      symbolName="testpoint_right"
      schX={2.8}
      schY={-0.01}
    />

    {/* VBUS feeds ZLOAD */}
    <trace from=".VBUS_RAIL > .1" to=".Z_LOAD > .1" />

    {/* ZLOAD/RSHUNT junction drives the noninverting input */}
    <trace path={[".Z_LOAD > .2", ".R_SHUNT > .pin1", ".U1_OPAMP > .inp1"]} />

    {/* RSHUNT returns to ground */}
    <trace from=".R_SHUNT > .pin2" to=".GND_SHUNT > .1" />

    {/* amplifier output is VOUT and feeds RF */}
    <trace path={[".U1_OPAMP > .out", ".R_F > .pin1", ".VOUT_TERMINAL > .1"]} />

    {/* RF/RG gain divider feeds the inverting input */}
    <trace
      path={[".R_F > .pin2", ".R_G > .pin1", ".U1_OPAMP > .inp2"]}
      schematicRouteHints={[
        { x: -0.8, y: -0.14 },
        { x: -0.8, y: -0.95 },
        { x: 1.5, y: -0.95 },
      ]}
    />

    {/* RG returns to ground */}
    <trace from=".R_G > .pin2" to=".GND_GAIN > .1" />

    {/* device positive supply is 5 V */}
    <trace from=".U1_OPAMP > .pin5" to=".V5_RAIL > .1" />

    {/* device negative supply returns to ground */}
    <trace from=".U1_OPAMP > .V-" to=".GND_DEVICE > .1" />

    <schematictext
      text="ILOAD"
      schX={-2.8}
      schY={1.35}
      fontSize={0.2}
      anchor="center"
    />

    <schematictext
      text="VSHUNT"
      schX={-2.8}
      schY={0.1}
      fontSize={0.2}
      anchor="center"
    />

    <schematictext
      text="TI OPA371D Figure 7-1"
      schX={0}
      schY={-3}
      fontSize={0.14}
      anchor="center"
    />
  </board>
);
