import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type CatalogEntry = {
  family: string;
  exportName: string;
  source: "existing" | "jlcpcb" | "ti-datasheet";
  componentExportName?: string;
};

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const chipDirectory = join(repositoryRoot, "lib/chips");
const catalogPath = join(chipDirectory, "ti-sysblocks-chip-catalog.json");
const outputPath = join(chipDirectory, "ti-sysblocks-components.tsx");

const catalog = (await Bun.file(catalogPath).json()) as CatalogEntry[];
const entries = [...catalog].sort((left, right) =>
  left.exportName.localeCompare(right.exportName),
);

const imports = entries.map((entry) => {
  const componentName = entry.componentExportName ?? entry.exportName;
  return `import { ${componentName} } from "./${componentName}.circuit.tsx";`;
});

const exactExports = entries
  .filter((entry) => entry.source !== "existing")
  .map((entry) => entry.componentExportName!)
  .sort((left, right) => left.localeCompare(right));

const aliases = entries.flatMap((entry) => {
  if (entry.source === "existing") return [];
  if (entry.exportName === entry.componentExportName) return [];
  return [
    `/** ${entry.family}, using the canonical package recorded in ti-sysblocks-chip-catalog.json. */`,
    `export const ${entry.exportName} = ${entry.componentExportName};`,
  ];
});

const source = `// This file is generated by scripts/generate-ti-sysblocks-exports.ts.
// Do not edit it by hand; update ti-sysblocks-chip-catalog.json and regenerate.

${imports.join("\n")}

export {
${exactExports.map((name) => `  ${name},`).join("\n")}
};

${aliases.join("\n")}

/** All TI product-family recommendations found in tscircuit/ti-sysblocks. */
export const TiSysblocksChipComponents = {
${entries.map((entry) => `  ${entry.exportName},`).join("\n")}
} as const;

export type TiSysblocksChipName = keyof typeof TiSysblocksChipComponents;
export type TiSysblocksChipComponent =
  (typeof TiSysblocksChipComponents)[TiSysblocksChipName];
`;

await Bun.write(outputPath, source);
console.log(`Generated ${entries.length} family exports in ${outputPath}`);
